default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_on_rails_template_development

test:
  <<: *default
  database: ruby_on_rails_template_test

production:
  <<: *default
  database: ruby_on_rails_template_production
  username: ruby_on_rails_template
  password: <%= ENV['DATABASE_PASSWORD'] %>
