default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubocop_config_builder_development

test:
  <<: *default
  database: rubocop_config_builder_test

production:
  <<: *default
  database: rubocop_config_builder_production
  username: rubocop_config_builder
  password: <%= ENV['GAMFILE_DATABASE_PASSWORD'] %>
