name: Linter
on: [pull_request]

jobs:
  ruby-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  haml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: HAML Lint
      uses: chiefpansancolt/haml-lint-action@add-additional-gems
      with:
        addition_gems: rubocop-rails rubocop-performance
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          eslint_flags: 'app/**/* postcss.config.js babel.config.js'

  css-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          stylelint_input: 'app/**/*.scss'
