name: Tests

on: [pull_request]

jobs:
  ruby-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Set up Ruby 2.6.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build and create DB
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        sudo apt-get install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:prepare
        bundle exec rake test
